### ISSUE TITLE
NPCDestinations_Farmer not working

### ISSUE THREAD

**Issue by Marcy135** [Nutty101/NPCDestinations_Farmer#1]
Hello,

i have a Problem with the Farmer Addon. I have created a NPC and followed the Steps and I get following Error:
```
[NPCDestinations_Farmer] Error:java.lang.NullPointerException
        at net.livecar.nuttyworks.destinations_farmer.plugin.Farmer_Processing.pluginTick(Farmer_Processing.java:100)
        at net.livecar.nuttyworks.destinations_farmer.DestFarmer_Plugin$1.run(DestFarmer_Plugin.java:74)
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71)
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353)
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:738)
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:405)
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:678)
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:576)
        at java.lang.Thread.run(Thread.java:748)
```

This Error is spaming in the Console after I used the Command /npcdest --npc 13 locfarmer 0 farm1 replant

I use WorldGuard but also without WorldGuard this Error is comming up
Server Version: Spigot 1.12
Plugin List: BungeePerms, BungeeServerSelector, Citizens v. 2.0.22, Destinations_Animations v. 2.6, Destinations_Farmers v. 2.6, Destinations_Rancher v. 1.2, Disable 1.12 Achivements, dtltraders v. 4.0.6, dynmap, iConomy, LightApi, NPC_Destinations v. 2.1.23, OldCombat, RTKPlugin, Sentinel v. 1.6.0, Vault, ViaVersion, worldedit v. 6.1.7.3, worldguard v. 6.2.2

I hope you find the mistake
Thanks

**Comment by Nutty101** [comment]
Need to snag 6.2.2. Thinking it might be related.

**Comment by Marcy135** [comment]
Do you have a solution for the problem?

**Comment by Nutty101** [comment]
Not yet, trying to get this working on 1.13 as well as resolve things like this at the same time.

**Comment by Nutty101** [comment]
Resolved in the 2.10 release. Not published just yet. It was looking for an item in the offhand and you don't have anything. Thus the error.

**Comment by Marcy135** [comment]
Server Version: Spigot 1.12
Plugin List: BungeePerms, BungeeServerSelector, Citizens v. 2.0.22, Destinations_Animations v. 2.6, Destinations_Farmers v. 2.6, Destinations_Rancher v. 1.2, Disable 1.12 Achivements, dtltraders v. 4.0.6, dynmap, iConomy, LightApi, NPC_Destinations v. 2.1.23, OldCombat, RTKPlugin, Sentinel v. 1.6.0, Vault, ViaVersion, worldedit v. 6.1.7.3, worldguard v. 6.2.2

I can´t join Discord.

Which Version´s do you use and which server version? (Worldguard, Main Plugin, Farmer Addon)

**Comment by Nutty101** [comment]
Would you be able to post a screenshot of what it's doing?
