### ISSUE TITLE
Cannot get data for not block WHEAT_SEEDS

### ISSUE THREAD

**Issue by Silverstar** [Nutty101/NPCDestinations_Farmer#12]
First, I guess you are heavily working on .13 / .14 support (and real live-living as well) so don't feel urged. Thank you for your work!

On version `git-Spigot-1a3504a-dfa7583 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)` with the plugins

<details><summary>Plugins</summary>
<p>BKCommonLib (1.13.2-v4-SNAPSHOT),
Citizens (2.0.25-SNAPSHOT (build 1692)),
dynmap (3.0-beta-3-160),
gravy (1.4.0),
LightAPI (3.2.8 (build - DEVELOPMENT)),
LuckPerms (4.4.1),
NPC_Destinations (2.3.29),
NPCDestinations_Farmer (2.3.5),
NPCDestinations_Rancher (2.3.1),
PlugMan (2.1.6),
ProtocolLib (4.5.0-SNAPSHOT),
Sentinel (1.9.1 (build 253)),
SignBoard (1.5.0),
SignEdit (1.6.0),
SignLink (1.13.1-v1),
WorldEdit (7.0.0-rc-2;7be00cc),
WorldGuard (7.0.0-rc-1;d542ba7),
Train_Carts (1.14-v1-SNAPSHOT)</p>
</details>

I get the exception

`[10:04:07 INFO]: [NPCDestinations_Farmer] Error:java.lang.IllegalArgumentException: Cannot get data for not block WHEAT_SEEDS
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:191)
        at org.bukkit.craftbukkit.v1_13_R2.block.data.CraftBlockData.newData(CraftBlockData.java:492)
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.createBlockData(CraftServer.java:1910)
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.createBlockData(CraftServer.java:1885)
        at org.bukkit.Bukkit.createBlockData(Bukkit.java:1376)
        at org.bukkit.Material.createBlockData(Material.java:3043)
        at org.bukkit.craftbukkit.v1_13_R2.block.CraftBlock.setType(CraftBlock.java:144)
        at org.bukkit.craftbukkit.v1_13_R2.block.CraftBlock.setType(CraftBlock.java:138)
        at net.livecar.nuttyworks.destinations_farmer.plugin.Processing.plantSeeds(Processing.java:358)
        at net.livecar.nuttyworks.destinations_farmer.plugin.Processing.pluginTick(Processing.java:129)
        at net.livecar.nuttyworks.destinations_farmer.BukkitPlugin$1.run(BukkitPlugin.java:81)
        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:81)
        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:392)
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:889)
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417)
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:831)
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:729)
        at java.lang.Thread.run(Thread.java:748)`

repeatedly until I disable it again via clicking the icon in the /nd info screen, so `issued server command: /npcdest enableplugin --npc 12 Farming` in the console.

Attached the citizens saves.yml (removed all except the patient, Bob).
[bob_saves.txt](https://github.com/Nutty101/NPCDestinations_Farmer/files/3186309/bob_saves.txt)

If any other file, log, detail is required, let me know.
Thank you in advance.

**Comment by Nutty101** [comment]
Can you try this version and see if it solves this for you?
http://jenkins.livecar.net/job/NPCDestinations_Farmer/lastSuccessfulBuild/artifact/target/NPCDestinations-Farmer-2_3_19.jar

**Comment by Silverstar** [comment]
Well, with Bob, I got the same error.
So I created a new NPC to sort that out. As long as he has a hoe in his mainhand, he tills everywhere around seeming random, even if distance set to 5 he runs away tilling every green he finds.
As soon as I give him wheat seeds (in the mainhand), the error reappers. I can't figure out to give it to the offhand ingame.

But additionally, while fiddling around, I also got another error :/

`[09:21:49 INFO]: [Citizens] Schwerwiegender Fehler während Update von 13: yaw not finite.
[09:21:49 WARN]: java.lang.IllegalArgumentException: yaw not finite
[09:21:49 WARN]:        at org.bukkit.util.NumberConversions.checkFinite(NumberConversions.java:124)
[09:21:49 WARN]:        at org.bukkit.Location.checkFinite(Location.java:589)
[09:21:49 WARN]:        at org.bukkit.craftbukkit.v1_13_R2.entity.CraftPlayer.teleport(CraftPlayer.java:580)
[09:21:49 WARN]:        at org.bukkit.craftbukkit.v1_13_R2.entity.CraftEntity.teleport(CraftEntity.java:311)
[09:21:49 WARN]:        at net.citizensnpcs.npc.ai.CitizensNavigator.stopNavigating(CitizensNavigator.java:291)
[09:21:49 WARN]:        at net.citizensnpcs.npc.ai.CitizensNavigator.stopNavigating(CitizensNavigator.java:307)
[09:21:49 WARN]:        at net.citizensnpcs.npc.ai.CitizensNavigator.run(CitizensNavigator.java:183)
[09:21:49 WARN]:        at net.citizensnpcs.npc.CitizensNPC.update(CitizensNPC.java:290)
[09:21:49 WARN]:        at net.citizensnpcs.nms.v1_13_R2.entity.EntityHumanNPC.tick(EntityHumanNPC.java:437)
[09:21:49 WARN]:        at net.minecraft.server.v1_13_R2.World.entityJoinedWorld(World.java:1331)
[09:21:49 WARN]:        at net.citizensnpcs.nms.v1_13_R2.util.NMSImpl.tick(NMSImpl.java:1053)
[09:21:49 WARN]:        at net.citizensnpcs.util.NMS.tick(NMS.java:391)
[09:21:49 WARN]:        at net.citizensnpcs.util.PlayerUpdateTask.run(PlayerUpdateTask.java:36)
[09:21:49 WARN]:        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:81)
[09:21:49 WARN]:        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:392)
[09:21:49 WARN]:        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:889)
[09:21:49 WARN]:        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417)
[09:21:49 WARN]:        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:831)
[09:21:49 WARN]:        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:729)
[09:21:49 WARN]:        at java.lang.Thread.run(Thread.java:748)
[09:21:50 INFO]: SilverstarX issued server command: /npc remove
[09:21:50 WARN]: java.lang.IllegalArgumentException: yaw not finite
[09:21:50 WARN]:        at org.bukkit.util.NumberConversions.checkFinite(NumberConversions.java:124)
[09:21:50 WARN]:        at org.bukkit.Location.checkFinite(Location.java:589)
[09:21:50 WARN]:        at org.bukkit.craftbukkit.v1_13_R2.entity.CraftPlayer.teleport(CraftPlayer.java:580)
[09:21:50 WARN]:        at org.bukkit.craftbukkit.v1_13_R2.entity.CraftEntity.teleport(CraftEntity.java:311)
[09:21:50 WARN]:        at net.citizensnpcs.npc.ai.CitizensNavigator.stopNavigating(CitizensNavigator.java:291)
[09:21:50 WARN]:        at net.citizensnpcs.npc.ai.CitizensNavigator.stopNavigating(CitizensNavigator.java:326)
[09:21:50 WARN]:        at net.citizensnpcs.npc.ai.CitizensNavigator.onDespawn(CitizensNavigator.java:138)
[09:21:50 WARN]:        at net.citizensnpcs.npc.CitizensNPC.despawn(CitizensNPC.java:87)
[09:21:50 WARN]:        at net.citizensnpcs.npc.CitizensNPCRegistry.deregister(CitizensNPCRegistry.java:68)
[09:21:50 WARN]:        at net.citizensnpcs.api.npc.AbstractNPC.destroy(AbstractNPC.java:155)
[09:21:50 WARN]:        at net.citizensnpcs.commands.NPCCommands.remove(NPCCommands.java:1402)
[09:21:50 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[09:21:50 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[09:21:50 WARN]:        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[09:21:50 WARN]:        at java.lang.reflect.Method.invoke(Method.java:498)
[09:21:50 WARN]:        at net.citizensnpcs.api.command.CommandManager.executeMethod(CommandManager.java:155)
[09:21:50 WARN]:        at net.citizensnpcs.api.command.CommandManager.execute(CommandManager.java:87)
[09:21:50 WARN]:        at net.citizensnpcs.api.command.CommandManager.executeSafe(CommandManager.java:183)
[09:21:50 WARN]:        at net.citizensnpcs.Citizens.onCommand(Citizens.java:263)
[09:21:50 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46)
[09:21:50 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[09:21:50 WARN]:        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:704)
[09:21:50 WARN]:        at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1621)
[09:21:50 WARN]:        at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1461)
[09:21:50 WARN]:        at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:45)
[09:21:50 WARN]:        at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:1)
[09:21:50 WARN]:        at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:9)
[09:21:50 WARN]:        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[09:21:50 WARN]:        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[09:21:50 WARN]:        at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199)
[09:21:50 WARN]:        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:896)
[09:21:50 WARN]:        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417)
[09:21:50 WARN]:        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:831)
[09:21:50 WARN]:        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:729)
[09:21:50 WARN]:        at java.lang.Thread.run(Thread.java:748)`

If I get some more time to test, I may set up a clean server with only Farmer and the dependencies installed.

**Comment by Silverstar** [comment]
I got offhand equip working... Now, with carrots offhand, he tills and plants carrots absolutely fine. But not with wheat seeds. Then, the error appears. Maybe the item name changed in 1.13 somehow so it won't work?
If I give him wheat offhand, he tills, but doesn't plant, even if wheat seeds are in the inventory. So wheat seeds are the problem...

**Comment by Nutty101** [comment]
Thanks, i will test that later and see what is up.
