### ISSUE TITLE
Error occurred while enabling NPCDestinations_Farmer v2.3.5

### ISSUE THREAD

**Issue by ErythroCraft** [Nutty101/NPCDestinations_Farmer#15]
Hi.

On server start the console has got an error.

[21:06:08] [Server thread/ERROR]: Error occurred while enabling NPCDestinations_Farmer v2.3.5 (Is it up to date?)
java.lang.LinkageError: loader org.bukkit.plugin.java.PluginClassLoader @7d058607 (instance of org.bukkit.plugin.java.PluginClassLoader, child of 'app' jdk.internal.loader.ClassLoaders$AppClassLoader) attempted duplicate class definition for org.apache.commons.io.FileUtils.
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
        at java.lang.ClassLoader.defineClass(ClassLoader.java:1016) ~[?:?]
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:163) ~[spigot.jar:3016-Spigot-73fb609-ea050e6]
        at org.bukkit.plugin.java.JavaPluginLoader.getClassByName(JavaPluginLoader.java:202) ~[spigot.jar:3016-Spigot-73fb609-ea050e6]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:107) ~[spigot.jar:3016-Spigot-73fb609-ea050e6]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:96) ~[spigot.jar:3016-Spigot-73fb609-ea050e6]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:588) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
        at net.livecar.nuttyworks.destinations_farmer.BukkitPlugin.exportConfig(BukkitPlugin.java:124) ~[?:?]
        at net.livecar.nuttyworks.destinations_farmer.BukkitPlugin.getDefaultConfigs(BukkitPlugin.java:114) ~[?:?]
        at net.livecar.nuttyworks.destinations_farmer.BukkitPlugin.onEnable(BukkitPlugin.java:60) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[spigot.jar:3016-Spigot-73fb609-ea050e6]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:351) ~[spigot.jar:3016-Spigot-73fb609-ea050e6]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[spigot.jar:3016-Spigot-73fb609-ea050e6]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:493) ~[spigot.jar:3016-Spigot-73fb609-ea050e6]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:407) ~[spigot.jar:3016-Spigot-73fb609-ea050e6]
        at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:435) ~[spigot.jar:3016-Spigot-73fb609-ea050e6]
        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:218) ~[spigot.jar:3016-Spigot-73fb609-ea050e6]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:809) ~[spigot.jar:3016-Spigot-73fb609-ea050e6]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[spigot.jar:3016-Spigot-73fb609-ea050e6]
        at java.lang.Thread.run(Thread.java:834) [?:?]

**Comment by ErythroCraft** [comment]
I'm using bukkit latest 1.16.5

I downloaded the newest version of this Plugin.
This day.

**Comment by Nutty101** [comment]
This tends to occur when someone has a plugin with an older version of the Commons.IO built in. Only way for me to fix is to stop using the commons IO.

**Comment by Nutty101** [comment]
@ErythroCraft this has been resolved. Please snag the new plugin, and addons.
