### ISSUE TITLE
NPE, presumably when trying to find nearby despawned Farmers

### ISSUE THREAD

**Issue by bbayu123** [Nutty101/NPCDestinations_Farmer#9]
`[19:28:10 INFO]: [NPCDestinations_Farmer] Error:java.lang.NullPointerException
        at net.livecar.nuttyworks.destinations_farmer.plugin.Processing.isFarmerNPCClose(Processing.java:509)
        at net.livecar.nuttyworks.destinations_farmer.plugin.Processing.locateNPCWork(Processing.java:446)
        at net.livecar.nuttyworks.destinations_farmer.plugin.Processing.pluginTick(Processing.java:286)
        at net.livecar.nuttyworks.destinations_farmer.BukkitPlugin$1.run(BukkitPlugin.java:81)
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76)
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:361)
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739)
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406)
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679)
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577)
        at java.lang.Thread.run(Unknown Source)`

**Comment by Nutty101** [comment]
Resolved
http://jenkins.livecar.net/job/NPCDestinations_Farmer/19/artifact/target/NPCDestinations-Farmer-2_3_19.jar
